### ISSUE TITLE
Could not start godot JS

### ISSUE THREAD

**Issue by Tilican** [d3dc/react-godot#1]
Hi,

Thx for your work !! But with godot 3.2 and this HTML 5 export :
![image](https://user-images.githubusercontent.com/10628316/73829150-ca562880-4802-11ea-8b97-b29cb7a79da5.png)

I can't launch my game but with your flappy game it works !

I got this error : 
![image](https://user-images.githubusercontent.com/10628316/73829246-f1acf580-4802-11ea-88f8-4297eb93af3e.png)

You can download my project there : https://github.com/evandikt/react-godot-test/

THX :)

**Comment by Tilican** [comment]
`instance.startGame` has now 2 params, the first is ExecName and second pck

**Comment by d3dc** [comment]
Not sure why the issue is closed now. If they've been updating the engine wrapper API, I'll look into doing some feature detection. I believe the build exports a constant I can check and then it's just a matter of how to represent different engine versions.

**Comment by MozarellaMan** [comment]
I'm getting the same issue. How exactly is this fixed? Sorry if it's obvious from the above messages
